job("Maven-Project-DSL") {
	description("Maven Job generated by the DSL on ${new Date()}, the project is a small sample hosted on github")
	scm {
		git("https://github.com/Roger2kTaylor/single-module.git", 'main')
        { node -> // is hudson.plugins.git.GitSCM
            node / gitConfigName('Roger2kTaylor')
            node / gitConfigEmail('roger@skye-nets.com')
        }
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package', 'Roger2kTaylor/single-module')
	}
	publishers {
		//archive the war file generated
		archiveArtifacts '**/*.jar'
	}
}